const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,body){const opt=body?{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(body)}:{credentials:'same-origin'};const r=await fetch(path,opt);const j=await r.json();if(r.status===401){showLogin(true);throw new Error('unauthorized')}if(!r.ok){const err=new Error(j.error||j.message||r.statusText);err.payload=j;throw err}return j}
function showLogin(v){$('login').classList.toggle('hidden',!v)}
async function login(user,password){const r=await fetch('/api/login',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:user,password})});if(r.ok)return '';const j=await r.json().catch(()=>({}));return r.status===429?(j.error||'Too many attempts; try again later'):'Invalid username or password'}
function toast(msg){$('toast').textContent=msg;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',3500)}
async function action(path,body){toast('Working…');try{const r=await api(path,body);toast(vramNote(r)||r.message||'Done');await loadDetails()}catch(e){const p=e.payload;if(p&&p.reason==='vram_conflict'&&!body.release_conflicts&&!body.force){const plan=p.vram_plan||{};const names=(plan.running||[]).filter(s=>(plan.release||[]).includes(s.id)).map(s=>`${s.mode||s.id} (~${s.estimated_vram_mib} MiB)`).join(', ');if(confirm(`${plan.message}\n\nRelease ${names} and continue? Restore brings them back.`))return action(path,{...body,release_conflicts:true});if(confirm('Start anyway? It may fail to load or slow the other servers.'))return action(path,{...body,force:true});toast('Not started: not enough GPU memory.');return}toast(e.message)}}
function vramNote(r){const p=r.vram_plan;if(!p)return '';if(p.released?.length)return `Released ${p.released.join(', ')} to make room. ${r.message||''}`;return ''}
const kLabel=n=>n>=1024?`${Math.round(n/1024)}K`:String(n);
let presets=[8192,16384,32768,65536,131072];
function btn(label,post,s,extra=''){return `<button data-post="${post}" data-server="${esc(s.id)}"${extra}>${label}</button>`}
function benchSpeed(b){const gen=`${esc(b.tokens_per_second??'—')} tok/s${b.tokens_per_second_source==='wall_clock'?' (wall clock)':''}`;return b.prompt_tokens_per_second?`${gen} gen · ${esc(b.prompt_tokens_per_second)} tok/s prompt`:gen}
function capsBits(c){if(!c)return [];const bits=[];const extra=(c.input||c.input_modalities||[]).filter(m=>m!=='text');if(extra.length)bits.push(extra.join('/'));if(c.tools)bits.push('tools');if(c.embedding)bits.push('embeddings');if(c.reranker)bits.push('reranker');return bits}
function capsLabel(c){if(!c)return '';const bits=[];if(c.slot_ctx)bits.push(`${kLabel(Number(c.slot_ctx))} per request${c.total_slots>1?` × ${c.total_slots} slots`:''}`);bits.push(...capsBits(c));return bits.length?` · ${esc(bits.join(' · '))}`:''}
function profileCaps(c){if(!c)return '';const bits=capsBits(c);if(c.context_max)bits.push(`trained ${kLabel(Number(c.context_max))} ctx`);if(c.vision_available)bits.push('projector found (set vision to enable)');const src=Object.entries(c.sources||{}).map(([k,v])=>`${k}: ${v}`).join(', ');return bits.length?` · <span title="${esc(src)}">${esc(bits.join(' · '))}</span>`:''}
let logSource=null;const LOG_LINES=2000;
function logAdd(t){const pre=$('logs');pre.append(t+'\n');while(pre.childNodes.length>LOG_LINES)pre.removeChild(pre.firstChild);if($('logs-follow').checked)pre.scrollTop=pre.scrollHeight}
function openLogs(id,name,history){if(logSource)logSource.close();$('logs-card').classList.remove('hidden');$('logs-title').textContent=name;if(history!==0)$('logs').textContent='';let opened=false;const es=new EventSource(`/api/logs/stream?server_id=${encodeURIComponent(id)}${history===0?'&history=0':''}`);logSource=es;
es.onopen=()=>{if(opened)$('logs').textContent='';opened=true};
es.addEventListener('lines',e=>{const d=JSON.parse(e.data);for(const l of d.lines)logAdd(d.stream==='stdout'?`[stdout] ${l}`:l)});
es.addEventListener('reset',()=>logAdd('— log restarted —'));
es.addEventListener('skipped',e=>logAdd(`— skipped ${JSON.parse(e.data).bytes} bytes to keep up —`));
es.addEventListener('end',e=>{const d=JSON.parse(e.data);es.close();if(d.reason==='timeout'&&logSource===es)return openLogs(id,name,0);logAdd(d.reason==='server_gone'?'— server is no longer tracked —':'— stream ended —')});
es.onerror=()=>{if(es.readyState===EventSource.CLOSED)logAdd('— disconnected —')}}
function closeLogs(){if(logSource){logSource.close();logSource=null}$('logs-card').classList.add('hidden')}
let samplingPresets=[];const chosenPreset={};
document.addEventListener('change',e=>{const m=e.target.dataset?.presetFor;if(m!=null)chosenPreset[m]=e.target.value});
function presetSelect(p){if(!samplingPresets.length)return '';const own=p.params?.sampling_preset;return `<select data-preset-for="${esc(p.mode)}" title="Sampling defaults for requests that do not set their own"><option value="">${own?`Profile (${esc(own)})`:'Profile sampling'}</option>${samplingPresets.map(x=>`<option value="${esc(x.key)}" title="${esc(x.description)}" ${chosenPreset[p.mode]===x.key?'selected':''}>${esc(x.label)}</option>`).join('')}<option value="none" ${chosenPreset[p.mode]==='none'?'selected':''}>No preset</option></select>`}
function defaultsLabel(d){const v=d?.values;if(!v)return '';const bits=[];if(v.temperature!=null)bits.push(`temp ${v.temperature}`);if(v.top_p!=null)bits.push(`top_p ${v.top_p}`);if(v.n_predict!=null)bits.push(`max ${v.n_predict}`);if(v.chat_template_kwargs)bits.push(Object.entries(v.chat_template_kwargs).map(([k,x])=>`${k}=${JSON.stringify(x)}`).join(' '));if(!bits.length&&!d.preset)return '';return ` · <span title="Defaults for requests that do not set their own values">defaults${d.preset?` ${esc(d.preset)}`:''}${bits.length?`: ${esc(bits.join(', '))}`:''}</span>`}
let idleDefault=0;const idlePresets=[0,900,1800,3600];
const idleLabel=n=>n?`${n>=3600?n/3600+'h':Math.round(n/60)+'m'}`:'off';
function idleRow(s){const own=s.idle_release_seconds;const cur=own??idleDefault;return `<div class="actions ctx"><span class="meta" title="Stop the server to free VRAM after this long without requests; Restore starts it again">Auto-release</span>${idlePresets.map(n=>`<button data-idle="${n}" data-server="${esc(s.id)}" ${cur===n?'disabled class="pill" title="current"':''}>${idleLabel(n)}</button>`).join('')}${own!=null&&own!==idleDefault?`<button data-idle="default" data-server="${esc(s.id)}" title="Use the app default (${idleLabel(idleDefault)})">default</button>`:''}</div>`}
function serverRow(s){const parked=s.status==='parked'||s.status==='restoring';const state=parked?(s.released_by==='idle'?'released after idle · GPU free':'released · GPU free'):s.suspended?'paused · model still in VRAM':s.running?'running':'stopped';let acts='';if(parked){acts=btn('Restore','/api/restore',s,' class="primary"')+btn('Forget','/api/stop',s)}else if(s.suspended){acts=btn('Resume','/api/resume',s)+btn('Stop','/api/stop',s)}else if(s.running){acts=btn('Pause','/api/suspend',s,' title="Freeze the process; the model stays in VRAM"')+btn('Release GPU','/api/release',s,' title="Stop the server to free VRAM; Restore starts it again"')+btn('Reload &amp; restart','/api/restart',s)+btn('Stop','/api/stop',s)}const ctx=(parked||(s.running&&!s.suspended))?`<div class="actions ctx"><span class="meta">Context</span>${presets.map(n=>{const cur=Number(s.ctx_size||s.overrides?.ctx_size)===n;return `<button data-post="${parked?'/api/restore':'/api/restart'}" data-server="${esc(s.id)}" data-ctx="${n}" ${cur?'disabled class="pill" title="current"':''}>${kLabel(n)}</button>`}).join('')}</div>`:'';acts+=`<button data-logs="${esc(s.id)}" data-name="${esc(s.mode||s.id)}">Logs</button>`;const idle=(s.running&&!s.suspended)?idleRow(s):'';return `<div class="row"><div><strong>${esc(s.mode||s.id)}</strong><div class="meta">${esc(state)} · PID ${esc(s.pid||'—')} · ${esc(s.host||'')}:${esc(s.port||'')}${s.ctx_size?` · ctx ${esc(kLabel(Number(s.ctx_size)))}`:''}${capsLabel(s.capabilities)}${defaultsLabel(s.request_defaults)}</div>${ctx}${idle}</div><div class="actions">${acts}</div></div>`}
async function runFit(mode){$('performance').innerHTML='<span class="muted">Running llama-fit-params…</span>';try{const r=await api('/api/fit',{mode});const s=r.speed_estimate||{};const h=r.suggestions?.headroom_mib;$('performance').innerHTML=`<div class="row"><div><strong>Fit: ${esc(mode)}</strong><div class="meta">${r.success?'completed':'failed'} · headroom ${esc(h??'—')} MiB · speed ${esc(s.low??s.min_tps??'—')}–${esc(s.high??s.max_tps??'—')} tok/s</div></div></div>`}catch(e){$('performance').textContent=e.message}}
async function setRemote(action,name){try{await api('/api/remote',{action,name});await refresh()}catch(e){toast(e.message)}}
async function runBenchmark(mode){$('performance').innerHTML='<span class="muted">Running benchmark…</span>';try{const r=await api('/api/benchmark',{mode,completion_tokens:128});const b=r.benchmark||{};$('performance').innerHTML=`<div class="row"><div><strong>Benchmark: ${esc(mode)}</strong><div class="meta">${benchSpeed(b)} · ${esc(b.elapsed_seconds??'—')} s</div></div></div>`;await loadDetails()}catch(e){$('performance').textContent=e.message}}
// Hardware, inventory and profiles run detection (subprocesses, directory scans):
// load them on start, after actions and once a minute, not on every 5 s status poll.
let profilesCache={profiles:[]};
function renderConfigProblems(r){const items=[...(r.errors||[]),...(r.warnings||[])];if(!items.length){$('config-problems').innerHTML='';return}const shown=items.slice(0,10).map(i=>`<div class="meta">${i.severity==='error'?'<strong>error</strong>':'warning'} · ${esc(i.file.split(/[\\/]/).pop())}${i.path?' '+esc(i.path):''}: ${esc(i.message)}</div>`).join('');$('config-problems').innerHTML=`<div class="row"><div><strong>Configuration: ${r.errors.length} error(s), ${r.warnings.length} warning(s)</strong>${shown}${items.length>10?`<div class="meta">…and ${items.length-10} more (run inferencedeck config validate)</div>`:''}</div></div>`}
async function loadDetails(){api('/api/config/check').then(renderConfigProblems).catch(()=>{});if(!samplingPresets.length){try{samplingPresets=(await api('/api/sampling')).presets||[]}catch(e){}}try{const [pr,inv,hw,bh]=await Promise.all([api('/api/profiles'),api('/api/inventory'),api('/api/hardware'),api('/api/benchmarks')]);profilesCache=pr;const cpu=hw.cpu||{};const gpu=hw.primary_gpu||{};const mem=hw.memory||{};$('hardware').textContent=`${cpu.model||cpu.name||'CPU unknown'} · ${gpu.name||'GPU not detected'} · ${gpu.vram_gb??gpu.memory_gb??'—'} GB VRAM · headroom target ${hw.recommended_fit_target_mib??'—'} MiB`;const sum=inv.summary||{};$('inventory').textContent=`${sum.model_count??0} models · ${sum.environment_count??0} runtimes · ${sum.profile_count??0} profiles`;$('benchmarks').innerHTML=(bh.benchmarks||[]).slice(-5).reverse().map(b=>`<div class="row"><div><strong>${esc(b.mode)}</strong><div class="meta">${benchSpeed(b)} · ${esc(b.created_at)}</div></div></div>`).join('')||'<span class="muted">No benchmarks recorded.</span>';}catch(e){}await refresh()}
async function refresh(){try{const [st,rm]=await Promise.all([api('/api/status'),api('/api/remotes')]);const pr=profilesCache;$('api-state').textContent='control API online';if(Array.isArray(st.context_presets))presets=st.context_presets;if(Number.isInteger(st.idle_release_default_seconds))idleDefault=st.idle_release_default_seconds;$('status').innerHTML=st.running_count?`<span class="pill">${st.running_count} running</span>`:'No tracked server is running.';$('servers').innerHTML=st.servers.length?st.servers.map(serverRow).join(''):'<span class="muted">No tracked servers.</span>';$('command').textContent=(st.servers.find(s=>s.running)||{}).command_line||'—';const remoteActive=!!rm.active;$('profiles').innerHTML=pr.profiles.length?pr.profiles.map(p=>`<div class="row"><div><strong>${esc(p.name||p.mode)}</strong><div class="meta">${esc(p.model?.name||'model unresolved')} · confidence ${esc(p.confidence)}${profileCaps(p.capabilities)}${remoteActive?' · local start disabled while remote active':''}</div></div><div class="actions">${presetSelect(p)}<button ${p.launchable?'':'disabled'} data-fit="${esc(p.mode)}">Fit</button><button ${p.launchable?'':'disabled'} data-bench="${esc(p.mode)}">Benchmark</button><button class="primary" ${p.launchable&&!remoteActive?'':'disabled'} data-post="/api/start" data-mode="${esc(p.mode)}">Start</button></div></div>`).join(''):'<span class="muted">No profiles found.</span>';$('remotes').innerHTML=(rm.endpoints||[]).map(r=>`<div class="row"><div><strong>${esc(r.display_name||r.name)}</strong><div class="meta">${esc(r.summary||r.provider+' · '+r.lane)} · ${!r.api_key_env?'no key':r.key_present?'key available':'set $'+esc(r.api_key_env)}</div></div>${r.enabled?'<span class="pill">active</span>':`<button ${r.selectable?'':'disabled'} data-remote="${esc(r.name)}">Enable</button>`}</div>`).join('')||'<span class="muted">No remote endpoints configured.</span>';}catch(e){$('api-state').textContent='control API error';$('status').textContent=e.message}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const d=b.dataset;if(d.post){const body=d.server?{server_id:d.server}:{mode:d.mode};if(d.ctx)body.ctx_size=Number(d.ctx);if(d.post==='/api/start'&&d.mode){const sel=document.querySelector(`select[data-preset-for="${CSS.escape(d.mode)}"]`);if(sel&&sel.value)body.overrides={sampling_preset:sel.value}}action(d.post,body)}else if(d.idle)action('/api/idle',{server_id:d.server,seconds:d.idle==='default'?null:Number(d.idle)});else if(d.logs)openLogs(d.logs,d.name);else if(b.id==='logs-close')closeLogs();else if(d.fit)runFit(d.fit);else if(d.bench)runBenchmark(d.bench);else if(d.remote)setRemote('enable',d.remote)});
async function loadRuntime(){try{const r=await api('/api/runtime');const c=r.cpu||{};const cpu=c.x86===false?'not x86 (instruction-set checks skipped)':(c.avx2?'AVX2 supported':'AVX2 not supported');const sel=r.selected;const opts=[`<option value="auto" ${r.requested==='auto'?'selected':''}>Automatic</option>`].concat((r.candidates||[]).map(x=>`<option value="${esc(x.id)}" ${x.compatible?'':'disabled'} ${r.requested!=='auto'&&x.selected?'selected':''}>${esc(x.label)}${x.compatible?'':' — '+esc(x.incompatible_reason)}</option>`)).join('');$('runtime').innerHTML=`<div class="meta">${c.x86===false?esc('CPU: '+cpu):'CPU instruction sets: '+esc((c.features||[]).map(f=>f.toUpperCase().replace('_','.')).join(', ')||'unknown')}</div><div><strong>${sel?esc(sel.label):'No compatible build'}</strong>${sel?` <span class="meta">${esc(sel.path)}</span>`:''}</div><div class="meta">${esc(r.reason)}</div>${(r.warnings||[]).map(w=>`<div class="meta">⚠ ${esc(w)}</div>`).join('')}<div class="actions"><label class="meta" for="runtime-select">Runtime</label><select id="runtime-select">${opts}</select></div>`;$('runtime-select').addEventListener('change',async e=>{try{await api('/api/runtime',{runtime:e.target.value});toast('Runtime updated')}catch(err){toast(err.message)}loadRuntime()})}catch(e){$('runtime').textContent=e.message}}
loadRuntime();loadDetails();setInterval(refresh,5000);setInterval(loadDetails,60000);

$('login-form').addEventListener('submit',async e=>{e.preventDefault();const err=await login($('login-user').value,$('login-password').value);if(!err){$('login-password').value='';$('login-error').textContent='';showLogin(false);loadDetails();loadRuntime()}else{$('login-error').textContent=err}});fetch('/api/auth').then(r=>r.json()).then(a=>{if(a.username)$('login-user').value=a.username;if(!a.required)showLogin(false)});
