const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,body){const opt=body?{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(body)}:{credentials:'same-origin'};const r=await fetch(path,opt);const j=await r.json();if(r.status===401){showLogin(true);throw new Error('unauthorized')}if(!r.ok)throw new Error(j.error||j.message||r.statusText);return j}
function showLogin(v){$('login').classList.toggle('hidden',!v)}
async function login(user,password){const r=await fetch('/api/login',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:user,password})});if(r.ok)return '';const j=await r.json().catch(()=>({}));return r.status===429?(j.error||'Too many attempts; try again later'):'Invalid username or password'}
function toast(msg){$('toast').textContent=msg;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',3500)}
async function action(path,body){toast('Working…');try{const r=await api(path,body);toast(r.message||'Done');await loadDetails()}catch(e){toast(e.message)}}
const kLabel=n=>n>=1024?`${Math.round(n/1024)}K`:String(n);
let presets=[8192,16384,32768,65536,131072];
function btn(label,post,s,extra=''){return `<button data-post="${post}" data-server="${esc(s.id)}"${extra}>${label}</button>`}
function serverRow(s){const parked=s.status==='parked'||s.status==='restoring';const state=parked?'released · GPU free':s.suspended?'paused · model still in VRAM':s.running?'running':'stopped';let acts='';if(parked){acts=btn('Restore','/api/restore',s,' class="primary"')+btn('Forget','/api/stop',s)}else if(s.suspended){acts=btn('Resume','/api/resume',s)+btn('Stop','/api/stop',s)}else if(s.running){acts=btn('Pause','/api/suspend',s,' title="Freeze the process; the model stays in VRAM"')+btn('Release GPU','/api/release',s,' title="Stop the server to free VRAM; Restore starts it again"')+btn('Reload &amp; restart','/api/restart',s)+btn('Stop','/api/stop',s)}const ctx=(parked||(s.running&&!s.suspended))?`<div class="actions ctx"><span class="meta">Context</span>${presets.map(n=>{const cur=Number(s.ctx_size||s.overrides?.ctx_size)===n;return `<button data-post="${parked?'/api/restore':'/api/restart'}" data-server="${esc(s.id)}" data-ctx="${n}" ${cur?'disabled class="pill" title="current"':''}>${kLabel(n)}</button>`}).join('')}</div>`:'';return `<div class="row"><div><strong>${esc(s.mode||s.id)}</strong><div class="meta">${esc(state)} · PID ${esc(s.pid||'—')} · ${esc(s.host||'')}:${esc(s.port||'')}${s.ctx_size?` · ctx ${esc(kLabel(Number(s.ctx_size)))}`:''}</div>${ctx}</div><div class="actions">${acts}</div></div>`}
async function runFit(mode){$('performance').innerHTML='<span class="muted">Running llama-fit-params…</span>';try{const r=await api('/api/fit',{mode});const s=r.speed_estimate||{};const h=r.suggestions?.headroom_mib;$('performance').innerHTML=`<div class="row"><div><strong>Fit: ${esc(mode)}</strong><div class="meta">${r.success?'completed':'failed'} · headroom ${esc(h??'—')} MiB · speed ${esc(s.low??s.min_tps??'—')}–${esc(s.high??s.max_tps??'—')} tok/s</div></div></div>`}catch(e){$('performance').textContent=e.message}}
async function setRemote(action,name){try{await api('/api/remote',{action,name});await refresh()}catch(e){toast(e.message)}}
async function runBenchmark(mode){$('performance').innerHTML='<span class="muted">Running benchmark…</span>';try{const r=await api('/api/benchmark',{mode,completion_tokens:128});const b=r.benchmark||{};$('performance').innerHTML=`<div class="row"><div><strong>Benchmark: ${esc(mode)}</strong><div class="meta">${esc(b.tokens_per_second??'—')} tok/s · ${esc(b.elapsed_seconds??'—')} s</div></div></div>`;await loadDetails()}catch(e){$('performance').textContent=e.message}}
// Hardware, inventory and profiles run detection (subprocesses, directory scans):
// load them on start, after actions and once a minute, not on every 5 s status poll.
let profilesCache={profiles:[]};
async function loadDetails(){try{const [pr,inv,hw,bh]=await Promise.all([api('/api/profiles'),api('/api/inventory'),api('/api/hardware'),api('/api/benchmarks')]);profilesCache=pr;const cpu=hw.cpu||{};const gpu=hw.primary_gpu||{};const mem=hw.memory||{};$('hardware').textContent=`${cpu.model||cpu.name||'CPU unknown'} · ${gpu.name||'GPU not detected'} · ${gpu.vram_gb??gpu.memory_gb??'—'} GB VRAM · headroom target ${hw.recommended_fit_target_mib??'—'} MiB`;const sum=inv.summary||{};$('inventory').textContent=`${sum.model_count??0} models · ${sum.environment_count??0} runtimes · ${sum.profile_count??0} profiles`;$('benchmarks').innerHTML=(bh.benchmarks||[]).slice(-5).reverse().map(b=>`<div class="row"><div><strong>${esc(b.mode)}</strong><div class="meta">${esc(b.tokens_per_second)} tok/s · ${esc(b.created_at)}</div></div></div>`).join('')||'<span class="muted">No benchmarks recorded.</span>';}catch(e){}await refresh()}
async function refresh(){try{const [st,rm]=await Promise.all([api('/api/status'),api('/api/remotes')]);const pr=profilesCache;$('api-state').textContent='control API online';if(Array.isArray(st.context_presets))presets=st.context_presets;$('status').innerHTML=st.running_count?`<span class="pill">${st.running_count} running</span>`:'No tracked server is running.';$('servers').innerHTML=st.servers.length?st.servers.map(serverRow).join(''):'<span class="muted">No tracked servers.</span>';$('command').textContent=(st.servers.find(s=>s.running)||{}).command_line||'—';const remoteActive=!!rm.active;$('profiles').innerHTML=pr.profiles.length?pr.profiles.map(p=>`<div class="row"><div><strong>${esc(p.name||p.mode)}</strong><div class="meta">${esc(p.model?.name||'model unresolved')} · confidence ${esc(p.confidence)}${remoteActive?' · local start disabled while remote active':''}</div></div><div class="actions"><button ${p.launchable?'':'disabled'} data-fit="${esc(p.mode)}">Fit</button><button ${p.launchable?'':'disabled'} data-bench="${esc(p.mode)}">Benchmark</button><button class="primary" ${p.launchable&&!remoteActive?'':'disabled'} data-post="/api/start" data-mode="${esc(p.mode)}">Start</button></div></div>`).join(''):'<span class="muted">No profiles found.</span>';$('remotes').innerHTML=(rm.endpoints||[]).map(r=>`<div class="row"><div><strong>${esc(r.display_name||r.name)}</strong><div class="meta">${esc(r.summary||r.provider+' · '+r.lane)} · ${!r.api_key_env?'no key':r.key_present?'key available':'set $'+esc(r.api_key_env)}</div></div>${r.enabled?'<span class="pill">active</span>':`<button ${r.selectable?'':'disabled'} data-remote="${esc(r.name)}">Enable</button>`}</div>`).join('')||'<span class="muted">No remote endpoints configured.</span>';}catch(e){$('api-state').textContent='control API error';$('status').textContent=e.message}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const d=b.dataset;if(d.post){const body=d.server?{server_id:d.server}:{mode:d.mode};if(d.ctx)body.ctx_size=Number(d.ctx);action(d.post,body)}else if(d.fit)runFit(d.fit);else if(d.bench)runBenchmark(d.bench);else if(d.remote)setRemote('enable',d.remote)});
async function loadRuntime(){try{const r=await api('/api/runtime');const c=r.cpu||{};const cpu=c.x86===false?'not x86 (instruction-set checks skipped)':(c.avx2?'AVX2 supported':'AVX2 not supported');const sel=r.selected;const opts=[`<option value="auto" ${r.requested==='auto'?'selected':''}>Automatic</option>`].concat((r.candidates||[]).map(x=>`<option value="${esc(x.id)}" ${x.compatible?'':'disabled'} ${r.requested!=='auto'&&x.selected?'selected':''}>${esc(x.label)}${x.compatible?'':' — '+esc(x.incompatible_reason)}</option>`)).join('');$('runtime').innerHTML=`<div class="meta">${c.x86===false?esc('CPU: '+cpu):'CPU instruction sets: '+esc((c.features||[]).map(f=>f.toUpperCase().replace('_','.')).join(', ')||'unknown')}</div><div><strong>${sel?esc(sel.label):'No compatible build'}</strong>${sel?` <span class="meta">${esc(sel.path)}</span>`:''}</div><div class="meta">${esc(r.reason)}</div>${(r.warnings||[]).map(w=>`<div class="meta">⚠ ${esc(w)}</div>`).join('')}<div class="actions"><label class="meta" for="runtime-select">Runtime</label><select id="runtime-select">${opts}</select></div>`;$('runtime-select').addEventListener('change',async e=>{try{await api('/api/runtime',{runtime:e.target.value});toast('Runtime updated')}catch(err){toast(err.message)}loadRuntime()})}catch(e){$('runtime').textContent=e.message}}
// Update checks detect every runtime and may ask GitHub (cached server-side for an
// hour), so they load on start, on "Check now" and every 30 minutes.
const releaseLink=u=>/^https:\/\/github\.com\//.test(u||'')?` <a href="${esc(u)}" target="_blank" rel="noopener noreferrer">release notes</a>`:'';
function updateRow(u){const state=u.update_available?'<span class="pill warn">update available</span>':u.latest_version?'<span class="pill">up to date</span>':'<span class="meta">latest unknown</span>';return `<div class="row"><div><strong>${esc(u.runtime_name)}</strong><div class="meta">installed ${esc(u.current_version)} · latest ${esc(u.latest_version||'—')} (${esc(u.channel)})${releaseLink(u.release_url)}${u.notes?' · '+esc(u.notes):''}</div></div>${state}</div>`}
async function loadUpdates(refresh){$('updates-check').disabled=true;try{const r=await api('/api/updates'+(refresh?'?refresh=1':''));const rows=(r.updates||[]).slice().sort((a,b)=>b.update_available-a.update_available).map(updateRow);const skipped=(r.skipped_no_version||[]).length?`<div class="muted">Not checked (no installed version found): ${esc(r.skipped_no_version.join(', '))}</div>`:'';$('updates').innerHTML=(rows.join('')||'<span class="muted">No installed runtime has a version to check.</span>')+skipped;if(refresh)toast('Update check finished')}catch(e){$('updates').innerHTML=`<span class="muted">${esc(e.message)}</span>`}$('updates-check').disabled=false}
$('updates-check').addEventListener('click',()=>loadUpdates(true));
loadRuntime();loadDetails();loadUpdates(false);setInterval(refresh,5000);setInterval(loadDetails,60000);setInterval(()=>loadUpdates(false),30*60000);

$('login-form').addEventListener('submit',async e=>{e.preventDefault();const err=await login($('login-user').value,$('login-password').value);if(!err){$('login-password').value='';$('login-error').textContent='';showLogin(false);loadDetails();loadRuntime();loadUpdates(false)}else{$('login-error').textContent=err}});fetch('/api/auth').then(r=>r.json()).then(a=>{if(a.username)$('login-user').value=a.username;if(!a.required)showLogin(false)});
